version: "3.9"

services:
  database:
    container_name: postgres-db
    restart: always
    image: postgres:16.0-alpine
    volumes:
      - ./postgres/postgres_data:/var/lib/postgresql/data
      - ./docker-entrypoint-initdb:/docker-entrypoint-initdb.d
      - ./docker-entrypoint-initdb/init-db/:/init-db
      - ./docker-entrypoint-initdb/seed/:/seed
      - ./queries/:/queries
    environment:
      POSTGRES_PASSWORD: ${ROOT_POSTGRES_PASSWORD:-secret}

      # User for creating in script
      POSTGRES_USER_DEV: ${POSTGRES_USER_DEV:-postgres_dev}
      POSTGRES_PASSWORD_DEV: ${POSTGRES_PASSWORD_DEV:-secret}
      POSTGRES_DB_DEV: ${POSTGRES_DB_DEV:-postgres_dev_bd}

    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER_DEV} -d ${POSTGRES_DB_DEV} " ]
      interval: 60s
      timeout: 5s
      retries: 5
    networks:
      - app-network
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"

    ports:
      - "5433:5432"

networks:
  app-network:
    driver: bridge

volumes:
  postgres_data:
    driver: local